import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { renderNodeToHTML, renderNodeToJSX } from "@ai-builder/serializers";
import type { LayoutTree } from "@ai-builder/schemas";

interface ExportPanelProps {
  tree: LayoutTree;
}

function downloadFile(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  // Defer revocation so the browser has time to start the download
  setTimeout(() => {
    URL.revokeObjectURL(url);
  }, 100);
}

function generateHTML(tree: LayoutTree): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <script src="https://cdn.tailwindcss.com"></script>
  <title>Layout Export</title>
</head>
<body>
${renderNodeToHTML(tree.root, 1)}
</body>
</html>`;
}

function generateJSX(tree: LayoutTree): string {
  return `// Layout component generated by AI Platform Builder
// Requires: React + Tailwind CSS

export function Layout() {
  return (
${renderNodeToJSX(tree.root, 2)}
  );
}
`;
}

export function ExportPanel({ tree }: ExportPanelProps) {
  return (
    <div className="space-y-2">
      <p className="text-muted-foreground text-xs">Export layout as:</p>
      <div className="flex flex-wrap gap-2">
        <Button
          variant="outline"
          size="sm"
          onClick={() => {
            downloadFile(generateHTML(tree), "layout.html", "text/html");
          }}
        >
          <Download className="mr-1.5 h-3.5 w-3.5" /> HTML
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => {
            downloadFile(generateJSX(tree), "Layout.tsx", "text/plain");
          }}
        >
          <Download className="mr-1.5 h-3.5 w-3.5" /> React JSX
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => {
            downloadFile(JSON.stringify(tree, null, 2), "layout.json", "application/json");
          }}
        >
          <Download className="mr-1.5 h-3.5 w-3.5" /> JSON
        </Button>
      </div>
    </div>
  );
}
